### ISSUE TITLE
关于论文

### ISSUE THREAD

**Issue by XuanYuannnn** [dyhBUPT/YYDS#2]
杜师兄您好，请问哪里可以看到您这篇YYDS的论文？

**Comment by dyhBUPT** [comment]
Hi, the paper was originally intended to be available at arxiv in March.
However, due to some sudden problems, the time will be delayed..... :sob: :sob: :sob:

**Comment by dyhBUPT** [comment]
Hi, our paper is now available at: https://arxiv.org/abs/2403.04183.
Thanks for your interest~

**Comment by XuanYuannnn** [comment]
谢谢师兄~
