### ISSUE TITLE
SYSU_YYDS模型权重问题

### ISSUE THREAD

**Issue by xyz999-skech** [dyhBUPT/YYDS#5]
作者您好，我在用您提供的SYSU_YYDS权重测试的时候会报以下错误
==> Building model..
/data/Herui/miniconda3/envs/svt/lib/python3.9/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
==> Loading data..
==> Resuming from checkpoint..
==> loading checkpoint /data/Herui/YYDS_files/SYSU_YYDS/sysu_deen_p4_n4_lr_0.1_seed_0_best.t
Traceback (most recent call last):
  File "/data/Herui/code/YYDS-master/test.py", line 99, in <module>
    checkpoint = torch.load(model_path)
  File "/data/Herui/miniconda3/envs/svt/lib/python3.9/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/data/Herui/miniconda3/envs/svt/lib/python3.9/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

通过对比发现SYSU_YYDS下的best权重文件只有几十兆大小，是否可能是上传时出现了错误？

**Comment by dyhBUPT** [comment]
Hi, thanks for your reminding!
I've update the ckpt file on baidu disk.
Please tell me if there are other issues.
